import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className=" flex flex-col min-h-screen">{children}</main>
      </body>
    </html>
  );
}
//bg-gradient-to-b from-black via-sky-400 to-gray-900
