import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className=" flex flex-col min-h-screen bg-gradient-to-b from-blue-100 to-red-100">
          {children}
        </div>
      </body>
    </html>
  );
}
//bg-gradient-to-b from-black via-sky-400 to-gray-900
